M48
; DRILL file {KiCad 7.0.6-0} date 2023 September 22, Friday 13:53:00
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-22T13:53:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X8.31Y-2.1801
X8.31Y-5.4301
X10.21Y-2.2301
X10.21Y-5.1801
T0
M30
